
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tickets}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

application:
  security:
    jwt:
      # openssl rand -hex 32
      secret-key: 2a472d4b6150645367566B5970337336763979244226452948404D635166546A
      expiration: 86400000 # 1 day

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
